version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: chatbot-backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    command: >
      uvicorn back.app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - PYTHONPATH=/app/back

  frontend:
    build:
      context: ./frontend
    container_name: chatbot-frontend
    ports:
      - "3000:80"       # Map host 3000 to container port 80 (Nginx default)
    depends_on:
      - backend
